# Generated by Django 6.1.1 on 2026-09-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_chamado_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração principal', max_length=100)),
                ('servidor_smtp', models.CharField(max_length=255)),
                ('porta_smtp', models.PositiveIntegerField(default=587)),
                ('usuario_smtp', models.EmailField(max_length=254)),
                ('senha_smtp', models.CharField(max_length=255)),
                ('usar_tls', models.BooleanField(default=True)),
                ('usar_ssl', models.BooleanField(default=False)),
                ('email_remetente', models.EmailField(max_length=254)),
                ('nome_remetente', models.CharField(default='Sistema de Chamados TI', max_length=100)),
                ('email_ti', models.EmailField(max_length=254, verbose_name='E-mail administrador TI')),
                ('ativo', models.BooleanField(default=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
